Repository netboxlabs/diode-sdk-python, pull requests merged in 2025-04, with the labels that each got.

#38 fix: include several missing many-many references
  netboxlabs/diode/sdk/diode/v1/ingester_pb2.py
  netboxlabs/diode/sdk/diode/v1/ingester_pb2.pyi
  netboxlabs/diode/sdk/ingester.py
Labels: python

#39 feat: update protobufs with additional custom field types
  netboxlabs/diode/sdk/diode/v1/ingester_pb2.py
  netboxlabs/diode/sdk/diode/v1/ingester_pb2.pyi
  netboxlabs/diode/sdk/ingester.py
  tests/test_ingester.py
Labels: python

#40 feat: adds oauth2 authentication
  .gitignore
  README.md
  netboxlabs/diode/sdk/client.py
  netboxlabs/diode/sdk/ingester.py
  pyproject.toml
  tests/test_client.py
Labels: github-actions, dependencies, markdown, python, internal

#41 chore: update dependencies to allow newer versions
  pyproject.toml
Labels: dependencies

#42 feat: wrap exceptions thrown while authenticating
  netboxlabs/diode/sdk/client.py
  tests/test_client.py
Labels: python

#43 feat: add OAuth2 diode:ingest scope to authentication process
  netboxlabs/diode/sdk/client.py
  tests/test_client.py
Labels: python

#44 perf: update supported entities list
  README.md
Labels: markdown

#46 🚀 release: 1.0.0
  .github/CODEOWNERS
  .github/workflows/lint-tests.yml
  .github/workflows/release.yaml
  .gitignore
  README.md
  netboxlabs/diode/sdk/client.py
  netboxlabs/diode/sdk/diode/v1/ingester_pb2.py
  netboxlabs/diode/sdk/diode/v1/ingester_pb2.pyi
  netboxlabs/diode/sdk/diode/v1/ingester_pb2_grpc.py
  netboxlabs/diode/sdk/ingester.py
  pyproject.toml
  tests/test_client.py
  tests/test_ingester.py
Labels: documentation, github-actions, dependencies, markdown, python, github-templates, internal
